Warning and error on stderr

diff --git a/driver/libexec/claw_f_lib.sh.in b/driver/libexec/claw_f_lib.sh.in
--- a/driver/libexec/claw_f_lib.sh.in
+++ b/driver/libexec/claw_f_lib.sh.in
@@ -240,10 +240,9 @@ function claw::print_version()
 ###################################################################
 function claw::error_exit()
 {
-  #TODO message
-    echo "internal:0:0: error: $1" >&2
-    echo "compilation aborted." >&2
-    exit 1
+  (>&2 echo "internal:0:0: error: $1")
+  (>&2 echo "compilation aborted.")
+  exit 1
 }
 
 
@@ -256,7 +255,7 @@ function claw::error_exit()
 ###################################################################
 function claw::warning()
 {
-  echo "$1:$2 warning: $3"
+  (>&2 echo "$1:$2 warning: $3")
 }
 
 
@@ -267,7 +266,7 @@ function claw::warning()
 ###################################################################
 function claw::verbose()
 {
-  [[ ${verbose} == true ]] && echo "$1"
+  [[ ${verbose} == true ]] && (>&2 echo "$1")
 }
 
 
